### ISSUE TITLE
define some way to use plugins in a target

### ISSUE THREAD

**Issue by arschles** [arschles/gocons#1]
maybe something like this:

``` yaml
targets:
  - name: mytarget
  - description: asdvsasd
  - plugin: something
  - params:
      param1: abc
      param2:
        - a
        - b
      param3:
        a: b
```
