### ISSUE TITLE
plugin: fallback

### ISSUE THREAD

**Issue by arschles** [arschles/gocons#3]
a plugin that can execute a list of commands until one succeeds. if none succeed, fail entirely. configured like this:

``` yaml
plugin: fallback
params:
  commands:
    - ./cmd1.sh
    - ./cmd2.sh
    - ./cmd3.sh
```

this may need to be further generalized into a pipeline.

depends on #1 to define plugin usage syntax
