### ISSUE TITLE
Look in the context dir for the Dockerfile

### ISSUE THREAD

**Issue by arschles** [arschles/gocons#58]
Even when a `gci.yaml` file is laid out like this:

``` yaml
<snip>
docker:
  image-name: quay.io/arschles/kubehttpbin
  tag: 0.0.1
  build:
    context:
      dir: rootfs/
</snip>
```

A `gci docker-build` from the root directory results in this error:

``` console
[ERROR] Reading Dockerfile ./Dockerfile [open ./Dockerfile: no such file or directory]
```

Notice that the context dir is `rootfs/`, so the command should look in `rootfs` for the `Dockerfile`
